apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokeservice
  namespace: jokenation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokeservice
  template:
    metadata:
      labels:
        app: jokeservice
    spec:
      containers:
        - name: jokeservice
          image: jokeservice:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
