apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoteservice
  template:
    metadata:
      labels:
        app: quoteservice
    spec:
      containers:
        - name: quoteservice
          image: quoteservice:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
